"""Add salt column to User model

Revision ID: 28d3f1fee956
Revises: 
Create Date: 2024-09-21 01:35:52.241885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d3f1fee956'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_units')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('salt')

    op.create_table('booking_units',
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name='booking_units_booking_id_fkey'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name='booking_units_unit_id_fkey'),
    sa.PrimaryKeyConstraint('booking_id', 'unit_id', name='booking_units_pkey')
    )
    # ### end Alembic commands ###
