"""Add booking_units table

Revision ID: 53070bdfda50
Revises: 
Create Date: 2024-10-10 16:24:36.139506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53070bdfda50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_units',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('booking_id', 'unit_id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('booking_unit_id_fkey', type_='foreignkey')
        batch_op.drop_column('unit_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('booking_unit_id_fkey', 'unit', ['unit_id'], ['id'])

    op.drop_table('booking_units')
    # ### end Alembic commands ###
